import { hiddenPaths } from "$lib/stores";
// hidden.json is generated by scaffold.ts alongside siteTree.ts
import hidden from "$lib/hidden.json";

export const prerender = true;
export const trailingSlash = "always";

// Populate the hiddenPaths store so FileTree can filter on the client
hiddenPaths.set(hidden);
