import * as fs from "fs";
import { Notice } from "obsidian";
import * as path from "path";

// ── Public API ─────────────────────────────────────────────────────────────

/**
 * Ensure `destRoot` is a ready-to-run SvelteKit project with the
 * Obsidian-style layout components in place.
 *
 * - If no `svelte.config.js` is found, runs `npx sv create` + `npm install`,
 *   then removes the boilerplate files that are not needed here.
 * - Copies all plugin-owned files from the `svelte-lib/` folder next to this
 *   file into the SvelteKit project. Files are always overwritten so that
 *   updates are applied on every export.
 *
 * Returns `false` if initialisation failed (caller should abort the export).
 */
export function ensureSvelteProject(
	destRoot: string,
	pluginDir: string,
	vaultPath: string,
): boolean {
	const isSvelteProject =
		fs.existsSync(path.join(destRoot, "svelte.config.js")) ||
		fs.existsSync(path.join(destRoot, "svelte.config.ts"));

	if (!isSvelteProject) {
		new Notice("🔧 No SvelteKit project detected — running npx sv create…");
		try {
			// eslint-disable-next-line @typescript-eslint/no-var-requires
			const { execSync } = require("child_process");

			const parentDir = path.dirname(destRoot);
			const projectName = path.basename(destRoot);

			execSync(
				`npx sv create "${projectName}" --template minimal --types ts --no-add-ons --no-install`,
				{ cwd: parentDir, stdio: "pipe" },
			);

			new Notice("📦 Running npm install…");
			execSync("npm install", { cwd: destRoot, stdio: "pipe" });

			// Remove boilerplate files generated by sv create that are not needed
			for (const name of [
				".npmrc",
				"README.md",
				".vscode",
				"src/routes/+layout.svelte",
			]) {
				removeIfExists(path.join(destRoot, name));
			}

			new Notice("✅ SvelteKit project initialised.");
		} catch (e) {
			console.error("[SvelteExporter] sv create failed:", e);
			new Notice(
				"❌ npx sv create failed. See console for details. " +
					"Create the project manually then re-export.",
			);
			return false;
		}
	}

	// If the existing layout was generated by sv create (contains favicon import),
	// remove it so copyPluginFiles can write the correct plugin layout.
	const layoutPath = path.join(destRoot, "src", "routes", "+layout.svelte");
	if (fs.existsSync(layoutPath)) {
		const existing = fs.readFileSync(layoutPath, "utf-8");
		if (existing.includes("favicon") || !existing.includes("app-shell")) {
			fs.unlinkSync(layoutPath);
		}
	}

	copyPluginFiles(destRoot, pluginDir, vaultPath);
	return true;
}

// ── Plugin-owned file copier ───────────────────────────────────────────────

/**
 * Recursively copy every file from `svelte-lib/` (shipped alongside the plugin)
 * into `destRoot/src/`, mirroring the directory structure exactly.
 * Files are always overwritten so updates are applied on every export.
 */
function copyPluginFiles(
	destRoot: string,
	pluginDir: string,
	vaultPath: string,
): void {
	const libDir = path.join(pluginDir, "svelte-lib");

	if (!fs.existsSync(libDir)) {
		console.error(
			"[SvelteExporter] svelte-lib/ folder not found next to plugin.",
		);
		new Notice("❌ svelte-lib/ folder missing from the plugin directory.");
		return;
	}

	// Copy svelte-lib/ → destRoot/src/
	const destSrc = path.join(destRoot, "src");
	copyRecursive(libDir, destSrc);

	// Copy Obsidian theme CSS files → destRoot/src/obsidian-css/theme/
	const obsidianDir = path.join(vaultPath, ".obsidian");
	const destCssDir = path.join(destRoot, "src", "obsidian-css");
	copyThemeCss(obsidianDir, destCssDir);
	copySnippetsCss(obsidianDir, destCssDir);
}

/**
 * Read .obsidian/appearance.json, find the active theme name (cssTheme),
 * and copy all *.css files from .obsidian/themes/<cssTheme>/ into destCssDir/theme/.
 */
function copyThemeCss(obsidianDir: string, destCssDir: string): void {
	const appearancePath = path.join(obsidianDir, "appearance.json");
	if (!fs.existsSync(appearancePath)) return;

	let cssTheme: string;
	try {
		const appearance = JSON.parse(fs.readFileSync(appearancePath, "utf-8"));
		cssTheme = appearance.cssTheme;
	} catch {
		console.warn("[SvelteExporter] Could not parse appearance.json");
		return;
	}

	if (!cssTheme) return;

	const themeDir = path.join(obsidianDir, "themes", cssTheme);
	const themeOut = path.join(destCssDir, "theme");
	if (!fs.existsSync(themeDir)) return;

	fs.mkdirSync(themeOut, { recursive: true });
	for (const entry of fs.readdirSync(themeDir, { withFileTypes: true })) {
		if (!entry.isFile() || !entry.name.endsWith(".css")) continue;
		fs.copyFileSync(
			path.join(themeDir, entry.name),
			path.join(themeOut, entry.name),
		);
	}
}

/**
 * Copy all *.css files from .obsidian/snippets/ into destCssDir/snippets/.
 */
function copySnippetsCss(obsidianDir: string, destCssDir: string): void {
	const snippetsDir = path.join(obsidianDir, "snippets");
	if (!fs.existsSync(snippetsDir)) return;

	const snippetsOut = path.join(destCssDir, "snippets");
	fs.mkdirSync(snippetsOut, { recursive: true });

	for (const entry of fs.readdirSync(snippetsDir, { withFileTypes: true })) {
		if (!entry.isFile() || !entry.name.endsWith(".css")) continue;
		fs.copyFileSync(
			path.join(snippetsDir, entry.name),
			path.join(snippetsOut, entry.name),
		);
	}
}

function copyRecursive(src: string, dest: string): void {
	fs.mkdirSync(dest, { recursive: true });
	for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
		const srcPath = path.join(src, entry.name);
		const destPath = path.join(dest, entry.name);
		if (entry.isDirectory()) {
			copyRecursive(srcPath, destPath);
		} else {
			fs.copyFileSync(srcPath, destPath);
		}
	}
}

// ── Filesystem helper ──────────────────────────────────────────────────────

function removeIfExists(target: string): void {
	if (!fs.existsSync(target)) return;
	if (fs.statSync(target).isDirectory()) {
		fs.readdirSync(target).forEach((child) =>
			removeIfExists(path.join(target, child)),
		);
		fs.rmdirSync(target);
	} else {
		fs.unlinkSync(target);
	}
}
