import * as fs from "fs";
import { Notice } from "obsidian";
import * as path from "path";

// ── Public API ─────────────────────────────────────────────────────────────

/**
 * Ensure `destRoot` is a ready-to-run SvelteKit project with the
 * Obsidian-style layout components in place.
 *
 * - If no `svelte.config.js` is found, runs `npx sv create` + `npm install`,
 *   then removes the boilerplate files that are not needed here.
 * - Copies all plugin-owned files from the `svelte-lib/` folder next to this
 *   file into the SvelteKit project. Files are always overwritten so that
 *   updates are applied on every export.
 *
 * Returns `false` if initialisation failed (caller should abort the export).
 */
export function ensureSvelteProject(
	destRoot: string,
	pluginDir: string,
	vaultPath: string,
	selectedTheme = "",
): boolean {
	const isSvelteProject =
		fs.existsSync(path.join(destRoot, "svelte.config.js")) ||
		fs.existsSync(path.join(destRoot, "svelte.config.ts"));

	if (!isSvelteProject) {
		new Notice("🔧 No SvelteKit project detected — running npx sv create…");
		try {
			// eslint-disable-next-line @typescript-eslint/no-var-requires
			const { execSync } = require("child_process");

			const parentDir = path.dirname(destRoot);
			const projectName = path.basename(destRoot);

			execSync(
				`npx sv create "${projectName}" --template minimal --types ts --no-add-ons --no-install`,
				{ cwd: parentDir, stdio: "pipe" },
			);

			new Notice("📦 Running npm install…");
			execSync("npm install", { cwd: destRoot, stdio: "pipe" });

			// Remove boilerplate files generated by sv create that are not needed
			for (const name of [
				".npmrc",
				"README.md",
				".vscode",
				"src/routes/+layout.svelte",
			]) {
				removeIfExists(path.join(destRoot, name));
			}

			new Notice("✅ SvelteKit project initialised.");
		} catch (e) {
			console.error("[SvelteExporter] sv create failed:", e);
			new Notice(
				"❌ npx sv create failed. See console for details. " +
					"Create the project manually then re-export.",
			);
			return false;
		}
	}

	// If the existing layout was generated by sv create (contains favicon import),
	// remove it so copyPluginFiles can write the correct plugin layout.
	const layoutPath = path.join(destRoot, "src", "routes", "+layout.svelte");
	if (fs.existsSync(layoutPath)) {
		const existing = fs.readFileSync(layoutPath, "utf-8");
		// Replace if it looks like the sv create boilerplate or is missing our marker
		if (
			existing.includes("favicon") ||
			!existing.includes("markdown-rendered")
		) {
			fs.unlinkSync(layoutPath);
		}
	}

	copyPluginFiles(destRoot, pluginDir, vaultPath, selectedTheme);
	return true;
}

// ── Plugin-owned file copier ───────────────────────────────────────────────

/**
 * Recursively copy every file from `svelte-lib/` (shipped alongside the plugin)
 * into `destRoot/src/`, mirroring the directory structure exactly.
 * Files are always overwritten so updates are applied on every export.
 */
function copyPluginFiles(
	destRoot: string,
	pluginDir: string,
	vaultPath: string,
	selectedTheme = "",
): void {
	const libDir = path.join(pluginDir, "svelte-lib");

	if (!fs.existsSync(libDir)) {
		console.error(
			"[SvelteExporter] svelte-lib/ folder not found next to plugin.",
		);
		new Notice("❌ svelte-lib/ folder missing from the plugin directory.");
		return;
	}

	// Delete static/ folder before copying (clean slate)
	removeIfExists(path.join(destRoot, "static"));

	// Copy svelte-lib/ → destRoot/src/
	// This always includes src/layout.css, which carries the reset, the
	// Obsidian-style layout shell, and icon-size overrides — so those rules
	// exist exactly once, regardless of which theme (if any) is selected.
	const destSrc = path.join(destRoot, "src");
	copyRecursive(libDir, destSrc);

	// Build app.css from Obsidian theme + snippets
	const obsidianDir = path.join(vaultPath, ".obsidian");
	buildAppCss(obsidianDir, path.join(destSrc, "app.css"), selectedTheme);
}

/**
 * Replace destRoot/src/app.css with the content of the active Obsidian theme
 * (if any) merged with all enabled snippets. If no theme is set, only
 * snippets are appended to the existing app.css.
 *
 * Layout shell / reset / icon-sizing rules are NOT duplicated here — they
 * live once in src/layout.css (shipped unconditionally by copyPluginFiles
 * and imported after app.css), so they keep working no matter what this
 * function writes into app.css.
 */
function buildAppCss(
	obsidianDir: string,
	appCssPath: string,
	selectedTheme = "",
): void {
	const appearancePath = path.join(obsidianDir, "appearance.json");
	let cssTheme = "";
	let enabledSnippets: string[] = [];

	if (fs.existsSync(appearancePath)) {
		try {
			const appearance = JSON.parse(
				fs.readFileSync(appearancePath, "utf-8"),
			);
			// selectedTheme="" → follow Obsidian; "__none__" → no theme; else → use named theme
			if (selectedTheme === "__none__") {
				cssTheme = "";
			} else if (selectedTheme !== "") {
				cssTheme = selectedTheme;
			} else {
				cssTheme = appearance.cssTheme ?? "";
			}
			enabledSnippets = appearance.enabledCssSnippets ?? [];
		} catch {
			console.warn("[SvelteExporter] Could not parse appearance.json");
		}
	} else if (selectedTheme !== "" && selectedTheme !== "__none__") {
		cssTheme = selectedTheme;
	}

	const chunks: string[] = [];

	if (cssTheme) {
		// Theme CSS replaces app.css as the base
		const themeDir = path.join(obsidianDir, "themes", cssTheme);
		if (fs.existsSync(themeDir)) {
			for (const entry of fs.readdirSync(themeDir, {
				withFileTypes: true,
			})) {
				if (!entry.isFile() || !entry.name.endsWith(".css")) continue;
				chunks.push(`/* theme: ${cssTheme}/${entry.name} */`);
				chunks.push(
					fs.readFileSync(path.join(themeDir, entry.name), "utf-8"),
				);
			}
		}
	} else {
		// No theme — keep the plugin's own app.css
		if (fs.existsSync(appCssPath)) {
			chunks.push(fs.readFileSync(appCssPath, "utf-8"));
		}
	}

	// Snippets (only enabled ones if the list is defined, otherwise all)
	const snippetsDir = path.join(obsidianDir, "snippets");
	if (fs.existsSync(snippetsDir)) {
		const allSnippets = fs
			.readdirSync(snippetsDir)
			.filter((f) => f.endsWith(".css"))
			.map((f) => f.replace(/\.css$/, ""));

		const toInclude =
			enabledSnippets.length > 0
				? allSnippets.filter((s) => enabledSnippets.includes(s))
				: allSnippets;

		for (const name of toInclude) {
			const filePath = path.join(snippetsDir, `${name}.css`);
			if (!fs.existsSync(filePath)) continue;
			chunks.push(`/* snippet: ${name}.css */`);
			chunks.push(fs.readFileSync(filePath, "utf-8"));
		}
	}

	if (chunks.length > 0) {
		fs.writeFileSync(appCssPath, chunks.join("\n\n"), "utf-8");
	}
}

function copyRecursive(src: string, dest: string): void {
	fs.mkdirSync(dest, { recursive: true });
	for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
		const srcPath = path.join(src, entry.name);
		const destPath = path.join(dest, entry.name);
		if (entry.isDirectory()) {
			copyRecursive(srcPath, destPath);
		} else {
			fs.copyFileSync(srcPath, destPath);
		}
	}
}

// ── Filesystem helper ──────────────────────────────────────────────────────

function removeIfExists(target: string): void {
	if (!fs.existsSync(target)) return;
	if (fs.statSync(target).isDirectory()) {
		fs.readdirSync(target).forEach((child) =>
			removeIfExists(path.join(target, child)),
		);
		fs.rmdirSync(target);
	} else {
		fs.unlinkSync(target);
	}
}
