import * as fs from "fs";
import { Notice } from "obsidian";
import * as path from "path";

// ── Public API ─────────────────────────────────────────────────────────────

/**
 * Ensure `destRoot` is a ready-to-run SvelteKit project with the
 * Obsidian-style layout components in place.
 *
 * - If no `svelte.config.js` is found, runs `npx sv create` + `npm install`,
 *   then removes the boilerplate files that are not needed here.
 * - Then writes all plugin-owned files (layout, components, CSS, stores…)
 *   without ever overwriting existing ones.
 *
 * Returns `false` if initialisation failed (caller should abort the export).
 */
export function ensureSvelteProject(destRoot: string): boolean {
	const isSvelteProject =
		fs.existsSync(path.join(destRoot, "svelte.config.js")) ||
		fs.existsSync(path.join(destRoot, "svelte.config.ts"));

	if (!isSvelteProject) {
		new Notice("🔧 No SvelteKit project detected — running npx sv create…");
		try {
			// eslint-disable-next-line @typescript-eslint/no-var-requires
			const { execSync } = require("child_process");

			const parentDir = path.dirname(destRoot);
			const projectName = path.basename(destRoot);

			execSync(
				`npx sv create "${projectName}" --template minimal --types ts --no-add-ons --no-install`,
				{ cwd: parentDir, stdio: "pipe" },
			);

			new Notice("📦 Running npm install…");
			execSync("npm install", { cwd: destRoot, stdio: "pipe" });

			// Remove boilerplate files generated by sv create that are not needed
			for (const name of [
				".npmrc",
				"README.md",
				".vscode",
				"src/routes/+layout.svelte",
			]) {
				removeIfExists(path.join(destRoot, name));
			}

			new Notice("✅ SvelteKit project initialised.");
		} catch (e) {
			console.error("[SvelteExporter] sv create failed:", e);
			new Notice(
				"❌ npx sv create failed. See console for details. " +
					"Create the project manually then re-export.",
			);
			return false;
		}
	}

	// If the existing layout was generated by sv create (contains favicon import),
	// remove it so writePluginFiles can write the correct plugin layout.
	const layoutPath = path.join(destRoot, "src", "routes", "+layout.svelte");
	if (fs.existsSync(layoutPath)) {
		const existing = fs.readFileSync(layoutPath, "utf-8");
		if (existing.includes("favicon") || !existing.includes("app-shell")) {
			fs.unlinkSync(layoutPath);
		}
	}

	writePluginFiles(destRoot);
	return true;
}

// ── Plugin-owned file writer ───────────────────────────────────────────────

/**
 * Write all files that belong to the plugin into the SvelteKit project.
 * Plugin-owned files are always overwritten so fixes are applied on each export.
 * User files (routes, pages) are never touched here.
 */
function writePluginFiles(destRoot: string): void {
	const write = (relPath: string, content: string) => {
		const abs = path.join(destRoot, relPath);
		fs.mkdirSync(path.dirname(abs), { recursive: true });
		fs.writeFileSync(abs, content, "utf-8");
	};

	write("src/app.css", APP_CSS);
	write("src/routes/+layout.svelte", LAYOUT_SVELTE);
	write("src/routes/+layout.ts", LAYOUT_TS);
	write("src/lib/stores.ts", STORES_TS);
	write("src/lib/siteTree.ts", SITE_TREE_TS);
	write("src/lib/markdownRenderer.ts", MARKDOWN_RENDERER_TS);
	write("src/lib/LeftSidebar.svelte", LEFT_SIDEBAR_SVELTE);
	write("src/lib/RightSidebar.svelte", RIGHT_SIDEBAR_SVELTE);
	write("src/lib/FileTree.svelte", FILE_TREE_SVELTE);
	write("src/lib/Graph.svelte", GRAPH_SVELTE);
	write("src/lib/Toc.svelte", TOC_SVELTE);
	write("src/routes/+page.svelte", HOME_PAGE_SVELTE);
}

// ── Filesystem helper ──────────────────────────────────────────────────────

function removeIfExists(target: string): void {
	if (!fs.existsSync(target)) return;
	if (fs.statSync(target).isDirectory()) {
		fs.readdirSync(target).forEach((child) =>
			removeIfExists(path.join(target, child)),
		);
		fs.rmdirSync(target);
	} else {
		fs.unlinkSync(target);
	}
}

// ── Source constants ───────────────────────────────────────────────────────

const STORES_TS = `import { writable } from 'svelte/store';

export interface TocHeading {
  id: string;
  text: string;
  level: number;
}

/** Headings of the currently displayed page, used by the ToC sidebar. */
export const tocHeadings = writable<TocHeading[]>([]);
`;

const LAYOUT_TS = `export const prerender = true;
export const trailingSlash = 'always';
`;

const HOME_PAGE_SVELTE = `<svelte:head><title>My Notes</title></svelte:head>

<div class="welcome">
  <h1>My Notes</h1>
  <p>Select a file in the left sidebar to start reading.</p>
</div>

<style>
  .welcome {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%;
    color: var(--text-muted);
  }
  .welcome h1 { font-size: 2rem; margin-bottom: .5rem; }
</style>
`;

const APP_CSS = `/* ── Obsidian-style design tokens ── */
:root {
  --bg-primary: #1e1e2e;
  --bg-secondary: #181825;
  --bg-tertiary: #11111b;
  --bg-modifier-hover: rgba(255,255,255,.06);
  --bg-modifier-border: #313244;
  --text-normal: #cdd6f4;
  --text-muted: #6c7086;
  --text-faint: #45475a;
  --text-accent: #89b4fa;
  --text-accent-hover: #b4d0ff;
  --interactive-accent: #89b4fa;
  --interactive-accent-hover: #b4d0ff;
  --code-bg: #181825;
  --code-fg: #cdd6f4;
  --blockquote-border: #89b4fa;
  --blockquote-bg: rgba(137,180,250,.08);
  --scrollbar-thumb: #45475a;
  --sidebar-width: 280px;
  --font-text: "Inter", system-ui, -apple-system, sans-serif;
  --font-mono: "Fira Code", "Cascadia Code", "JetBrains Mono", monospace;
  --font-size-base: 15px;
  --radius: 6px;
  color-scheme: dark;
}

[data-theme="light"] {
  --bg-primary: #fafaf8;
  --bg-secondary: #f0f0ea;
  --bg-tertiary: #e8e8e0;
  --bg-modifier-hover: rgba(0,0,0,.05);
  --bg-modifier-border: #ddd8cc;
  --text-normal: #1a1a1a;
  --text-muted: #6b6b6b;
  --text-faint: #aaa;
  --text-accent: #1e6fbf;
  --text-accent-hover: #1558a0;
  --interactive-accent: #1e6fbf;
  --interactive-accent-hover: #1558a0;
  --code-bg: #f0f0ea;
  --code-fg: #24292e;
  --blockquote-border: #1e6fbf;
  --blockquote-bg: rgba(30,111,191,.06);
  --scrollbar-thumb: #ccc;
  color-scheme: light;
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { font-size: var(--font-size-base); }

body {
  font-family: var(--font-text);
  background: var(--bg-primary);
  color: var(--text-normal);
  min-height: 100vh;
  overflow: hidden;
  line-height: 1.7;
}

::-webkit-scrollbar { width: 6px; height: 6px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: var(--scrollbar-thumb); border-radius: 3px; }

/* ── App shell ── */
.app-shell {
  display: grid;
  grid-template-columns: auto 1fr auto;
  height: 100vh;
  overflow: hidden;
}

/* ── Sidebars ── */
.sidebar {
  display: flex;
  flex-direction: column;
  background: var(--bg-secondary);
  overflow: hidden;
  transition: width .2s ease;
  position: relative;
  z-index: 10;
}
.sidebar.left  { border-right: 1px solid var(--bg-modifier-border); width: var(--sidebar-width); }
.sidebar.right { border-left:  1px solid var(--bg-modifier-border); width: var(--sidebar-width); }
.sidebar.collapsed { width: 36px; }

.sidebar-toolbar {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 6px 8px;
  border-bottom: 1px solid var(--bg-modifier-border);
  flex-shrink: 0;
  min-height: 40px;
}
.sidebar-body { flex: 1; overflow-y: auto; overflow-x: hidden; padding: 8px 0; }

.sidebar.collapsed .sidebar-body,
.sidebar.collapsed .sidebar-toolbar > *:not(.collapse-btn) { display: none; }
.sidebar.collapsed .sidebar-toolbar { justify-content: center; border-bottom-color: transparent; }

/* ── Icon buttons ── */
.icon-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border: none;
  background: transparent;
  color: var(--text-muted);
  border-radius: var(--radius);
  cursor: pointer;
  flex-shrink: 0;
  transition: background .15s, color .15s;
}
.icon-btn:hover { background: var(--bg-modifier-hover); color: var(--text-normal); }
.icon-btn svg { width: 16px; height: 16px; }

/* ── Search ── */
.search-wrap { flex: 1; position: relative; }
.search-wrap input {
  width: 100%;
  background: var(--bg-tertiary);
  border: 1px solid var(--bg-modifier-border);
  border-radius: var(--radius);
  color: var(--text-normal);
  font-size: .8rem;
  padding: 4px 8px 4px 28px;
  outline: none;
  transition: border-color .15s;
}
.search-wrap input::placeholder { color: var(--text-faint); }
.search-wrap input:focus { border-color: var(--interactive-accent); }
.search-wrap .search-icon {
  position: absolute; left: 7px; top: 50%; transform: translateY(-50%);
  color: var(--text-faint); pointer-events: none;
}
.search-wrap .search-icon svg { width: 13px; height: 13px; }

/* ── File tree ── */
.tree-item {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 2px 8px;
  cursor: pointer;
  font-size: .85rem;
  color: var(--text-normal);
  border-radius: var(--radius);
  text-decoration: none;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  transition: background .1s;
  user-select: none;
}
.tree-item:hover { background: var(--bg-modifier-hover); }
.tree-item.active { background: var(--bg-modifier-hover); color: var(--text-accent); }
.tree-item svg { flex-shrink: 0; width: 14px; height: 14px; color: var(--text-muted); }
.tree-folder-toggle { flex-shrink: 0; width: 14px; color: var(--text-faint); font-size: .6rem; }
.tree-children { display: none; }
.tree-children.open { display: block; }

/* ── Graph ── */
.graph-wrap { padding: 8px; }
.graph-canvas { width: 100%; aspect-ratio: 1; border-radius: var(--radius); background: var(--bg-tertiary); display: block; }
.graph-label { font-size: .7rem; color: var(--text-muted); text-align: center; padding: 2px 0 6px; }

/* ── ToC ── */
.toc-title {
  font-size: .7rem; font-weight: 600; text-transform: uppercase;
  letter-spacing: .08em; color: var(--text-muted); padding: 8px 12px 4px;
}
.toc-item {
  display: block; font-size: .8rem; color: var(--text-muted);
  padding: 2px 12px; text-decoration: none;
  border-left: 2px solid transparent; transition: color .1s, border-color .1s;
  white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
}
.toc-item:hover { color: var(--text-normal); }
.toc-item.active { color: var(--text-accent); border-left-color: var(--interactive-accent); }
.toc-item.h1 { padding-left: 12px; }
.toc-item.h2 { padding-left: 20px; }
.toc-item.h3 { padding-left: 28px; }
.toc-item.h4 { padding-left: 36px; }

/* ── Content area ── */
.content-area { overflow-y: auto; overflow-x: hidden; height: 100vh; background: var(--bg-primary); }

/* ── Markdown page ── */
.md-page { max-width: 72ch; margin: 0 auto; padding: 3rem 2rem 6rem; }
.md-header { margin-bottom: 2.5rem; padding-bottom: 1.25rem; border-bottom: 1px solid var(--bg-modifier-border); }
.md-header h1 { font-size: 2rem; font-weight: 700; line-height: 1.2; color: var(--text-normal); }
.md-header .description { color: var(--text-muted); font-style: italic; margin-top: .5rem; }

.md-content h1, .md-content h2, .md-content h3,
.md-content h4, .md-content h5, .md-content h6 {
  font-weight: 600; margin: 1.75em 0 .5em; line-height: 1.3;
  color: var(--text-normal); scroll-margin-top: 1rem;
}
.md-content h1 { font-size: 1.75rem; }
.md-content h2 { font-size: 1.35rem; border-bottom: 1px solid var(--bg-modifier-border); padding-bottom: .25em; }
.md-content h3 { font-size: 1.1rem; }
.md-content p  { margin: .9em 0; }
.md-content a  { color: var(--text-accent); text-decoration: underline; text-underline-offset: 2px; }
.md-content a:hover { color: var(--text-accent-hover); }
.md-content code {
  font-family: var(--font-mono); background: var(--code-bg); color: var(--code-fg);
  padding: .15em .4em; border-radius: 4px; font-size: .875em;
}
.md-content pre {
  background: var(--code-bg); border: 1px solid var(--bg-modifier-border);
  border-radius: var(--radius); padding: 1.25rem; overflow-x: auto;
  font-size: .875rem; line-height: 1.6; margin: 1em 0;
}
.md-content pre code { background: none; padding: 0; font-size: inherit; color: inherit; }
.md-content blockquote {
  margin: 1.25em 0; padding: .5em 1.25em;
  border-left: 3px solid var(--blockquote-border);
  background: var(--blockquote-bg); color: var(--text-muted); font-style: italic;
}
.md-content ul, .md-content ol { padding-left: 1.75rem; margin: .75em 0; }
.md-content li { margin: .3em 0; }
.md-content table { width: 100%; border-collapse: collapse; margin: 1.25em 0; font-size: .9rem; }
.md-content th, .md-content td { border: 1px solid var(--bg-modifier-border); padding: .5rem .75rem; text-align: left; }
.md-content th { background: var(--bg-secondary); font-weight: 600; }
.md-content img { max-width: 100%; border-radius: var(--radius); margin: 1em 0; }
.md-content hr { border: none; border-top: 1px solid var(--bg-modifier-border); margin: 2em 0; }
.md-content input[type="checkbox"] { margin-right: .4em; }
.md-content strong { color: var(--text-normal); }
.md-content em { color: var(--text-muted); }
`;

const LAYOUT_SVELTE = `<script lang="ts">
  import type { Snippet } from 'svelte';
  import LeftSidebar from '$lib/LeftSidebar.svelte';
  import RightSidebar from '$lib/RightSidebar.svelte';
  import '../app.css';

  const { children }: { children: Snippet } = $props();

  let theme: 'dark' | 'light' = $state('dark');

  function toggleTheme() {
    theme = theme === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', theme);
  }
</script>

<div class="app-shell">
  <LeftSidebar />
  <main class="content-area">
    {@render children()}
  </main>
  <RightSidebar {theme} {toggleTheme} />
</div>
`;

const LEFT_SIDEBAR_SVELTE = `<script lang="ts">
  import { page } from '$app/stores';
  import FileTree from '$lib/FileTree.svelte';

  let collapsed = $state(false);
  let query = $state('');
</script>

<aside class="sidebar left" class:collapsed>
  <div class="sidebar-toolbar">
    <div class="search-wrap">
      <span class="search-icon">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>
        </svg>
      </span>
      <input type="search" placeholder="Search…" bind:value={query} />
    </div>
    <button class="icon-btn collapse-btn"
      onclick={() => collapsed = !collapsed}
      title={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        {#if collapsed}<path d="M9 18l6-6-6-6"/>
        {:else}<path d="M15 18l-6-6 6-6"/>
        {/if}
      </svg>
    </button>
  </div>
  <div class="sidebar-body">
    <FileTree {query} currentPath={$page.url.pathname} />
  </div>
</aside>
`;

const RIGHT_SIDEBAR_SVELTE = `<script lang="ts">
  import Graph from '$lib/Graph.svelte';
  import Toc from '$lib/Toc.svelte';

  interface Props { theme: 'dark' | 'light'; toggleTheme: () => void; }
  const { theme, toggleTheme }: Props = $props();

  let collapsed = $state(false);
</script>

<aside class="sidebar right" class:collapsed>
  <div class="sidebar-toolbar">
    <button class="icon-btn collapse-btn"
      onclick={() => collapsed = !collapsed}
      title={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        {#if collapsed}<path d="M15 18l-6-6 6-6"/>
        {:else}<path d="M9 18l6-6-6-6"/>
        {/if}
      </svg>
    </button>
    <button class="icon-btn" onclick={toggleTheme} title="Toggle light/dark mode">
      {#if theme === 'dark'}
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <circle cx="12" cy="12" r="5"/>
          <path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"/>
        </svg>
      {:else}
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>
        </svg>
      {/if}
    </button>
  </div>
  <div class="sidebar-body">
    <Graph />
    <Toc />
  </div>
</aside>
`;

const FILE_TREE_SVELTE = `<script lang="ts">
  import { siteTree, type TreeNode } from '$lib/siteTree';

  interface Props { query: string; currentPath: string; }
  const { query, currentPath }: Props = $props();

  function matchesQuery(node: TreeNode, q: string): boolean {
    if (!q) return true;
    const lower = q.toLowerCase();
    if (node.name.toLowerCase().includes(lower)) return true;
    if (node.children) return node.children.some(c => matchesQuery(c, q));
    return false;
  }

  let openFolders: Record<string, boolean> = $state({});
  const toggle = (p: string) => { openFolders[p] = !openFolders[p]; };
  const filteredTree = $derived(query ? siteTree.filter(n => matchesQuery(n, query)) : siteTree);
</script>

<nav>
  {#each filteredTree as node}
    {#if node.children}
      <div style="padding-left: {node.depth * 12}px">
        <div class="tree-item"
          onclick={() => toggle(node.path)}
          onkeydown={e => e.key === 'Enter' && toggle(node.path)}
          role="button" tabindex="0">
          <span class="tree-folder-toggle">{openFolders[node.path] ? '▼' : '▶'}</span>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/>
          </svg>
          <span>{node.name}</span>
        </div>
        <div class="tree-children" class:open={openFolders[node.path] || !!query}>
          {#each (node.children ?? []) as child}
            {#if child.children}
              <div style="padding-left: {child.depth * 12}px">
                <div class="tree-item"
                  onclick={() => toggle(child.path)}
                  onkeydown={e => e.key === 'Enter' && toggle(child.path)}
                  role="button" tabindex="0">
                  <span class="tree-folder-toggle">{openFolders[child.path] ? '▼' : '▶'}</span>
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/>
                  </svg>
                  <span>{child.name}</span>
                </div>
                <div class="tree-children" class:open={openFolders[child.path] || !!query}>
                  {#each (child.children ?? []) as leaf}
                    <a href={leaf.path} class="tree-item" class:active={currentPath === leaf.path}
                      style="padding-left: {leaf.depth * 12 + 8}px">
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                        <polyline points="14 2 14 8 20 8"/>
                      </svg>
                      <span>{leaf.name}</span>
                    </a>
                  {/each}
                </div>
              </div>
            {:else}
              <a href={child.path} class="tree-item" class:active={currentPath === child.path}
                style="padding-left: {child.depth * 12 + 8}px">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                  <polyline points="14 2 14 8 20 8"/>
                </svg>
                <span>{child.name}</span>
              </a>
            {/if}
          {/each}
        </div>
      </div>
    {:else}
      <a href={node.path} class="tree-item" class:active={currentPath === node.path}
        style="padding-left: {node.depth * 12 + 8}px">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
          <polyline points="14 2 14 8 20 8"/>
        </svg>
        <span>{node.name}</span>
      </a>
    {/if}
  {/each}
</nav>
`;

const GRAPH_SVELTE = `<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { siteTree, flattenTree } from '$lib/siteTree';

  let canvas: HTMLCanvasElement;

  interface GNode { id: string; label: string; x: number; y: number; vx: number; vy: number; }
  interface GLink { source: string; target: string; }

  const files = flattenTree(siteTree);
  const nodes: GNode[] = files.map(f => ({
    id: f.path, label: f.name,
    x: Math.random() * 200 + 20, y: Math.random() * 200 + 20, vx: 0, vy: 0,
  }));

  const links: GLink[] = [];
  files.forEach(f => {
    const parts = f.path.split('/').filter(Boolean);
    if (parts.length > 1) {
      const parentPath = '/' + parts.slice(0, -1).join('/') + '/';
      if (nodes.find(n => n.id === parentPath))
        links.push({ source: parentPath, target: f.path });
    }
  });

  const SZ = 240;

  function simulate() {
    const cx = SZ / 2, cy = SZ / 2;
    for (let iter = 0; iter < 80; iter++) {
      for (let i = 0; i < nodes.length; i++) {
        for (let j = i + 1; j < nodes.length; j++) {
          const dx = nodes[j].x - nodes[i].x, dy = nodes[j].y - nodes[i].y;
          const dist = Math.sqrt(dx*dx + dy*dy) || 1;
          const force = 400 / (dist * dist);
          nodes[i].vx -= force*dx/dist; nodes[i].vy -= force*dy/dist;
          nodes[j].vx += force*dx/dist; nodes[j].vy += force*dy/dist;
        }
      }
      links.forEach(l => {
        const s = nodes.find(n => n.id === l.source)!;
        const t = nodes.find(n => n.id === l.target)!;
        if (!s || !t) return;
        const dx = t.x - s.x, dy = t.y - s.y;
        const dist = Math.sqrt(dx*dx + dy*dy) || 1;
        const force = dist * 0.05;
        s.vx += force*dx/dist; s.vy += force*dy/dist;
        t.vx -= force*dx/dist; t.vy -= force*dy/dist;
      });
      nodes.forEach(n => {
        n.vx += (cx - n.x) * 0.01; n.vy += (cy - n.y) * 0.01;
        n.x += n.vx * 0.5; n.y += n.vy * 0.5;
        n.vx *= 0.7; n.vy *= 0.7;
        n.x = Math.max(8, Math.min(SZ-8, n.x));
        n.y = Math.max(8, Math.min(SZ-8, n.y));
      });
    }
  }

  function draw(currentPath: string) {
    if (!canvas) return;
    const ctx = canvas.getContext('2d')!;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = SZ * dpr; canvas.height = SZ * dpr;
    canvas.style.width = SZ + 'px'; canvas.style.height = SZ + 'px';
    ctx.scale(dpr, dpr);
    const isDark = document.documentElement.getAttribute('data-theme') !== 'light';
    ctx.clearRect(0, 0, SZ, SZ);
    links.forEach(l => {
      const s = nodes.find(n => n.id === l.source)!;
      const t = nodes.find(n => n.id === l.target)!;
      if (!s || !t) return;
      ctx.beginPath(); ctx.moveTo(s.x, s.y); ctx.lineTo(t.x, t.y);
      ctx.strokeStyle = isDark ? '#45475a' : '#d0cfc5'; ctx.lineWidth = 1; ctx.stroke();
    });
    nodes.forEach(n => {
      const isCurrent = n.id === currentPath || n.id === currentPath + '/';
      ctx.beginPath(); ctx.arc(n.x, n.y, isCurrent ? 6 : 4, 0, Math.PI*2);
      ctx.fillStyle = isCurrent
        ? (isDark ? '#89b4fa' : '#1e6fbf')
        : (isDark ? '#585b70' : '#bbbbc8');
      ctx.fill();
      if (isCurrent) {
        ctx.font = 'bold 9px system-ui';
        ctx.fillStyle = isDark ? '#cdd6f4' : '#1a1a1a';
        ctx.fillText(n.label, n.x + 8, n.y + 4);
      }
    });
  }

  onMount(() => {
    simulate();
    const unsub = page.subscribe(p => draw(p.url.pathname));
    return unsub;
  });
</script>

<div class="graph-wrap">
  <div class="graph-label">Graph view</div>
  <canvas class="graph-canvas" bind:this={canvas}></canvas>
</div>
`;

const TOC_SVELTE = `<script lang="ts">
  import { onMount } from 'svelte';
  import { tocHeadings } from '$lib/stores';

  let active = $state('');

  onMount(() => {
    const observer = new IntersectionObserver(
      entries => {
        for (const e of entries) {
          if (e.isIntersecting) { active = e.target.id; break; }
        }
      },
      { rootMargin: '0px 0px -70% 0px', threshold: 0 }
    );
    const unsub = tocHeadings.subscribe(headings => {
      observer.disconnect();
      headings.forEach(h => {
        const el = document.getElementById(h.id);
        if (el) observer.observe(el);
      });
    });
    return () => { observer.disconnect(); unsub(); };
  });
</script>

{#if $tocHeadings.length > 0}
  <div class="toc-title">On this page</div>
  {#each $tocHeadings as h}
    <a href="#{h.id}" class="toc-item h{h.level}" class:active={active === h.id}>
      {h.text}
    </a>
  {/each}
{/if}
`;

const MARKDOWN_RENDERER_TS = `/**
 * Lightweight Markdown → HTML renderer.
 * No external dependencies — safe to use in any Svelte/SvelteKit project.
 */
export function renderMarkdown(md: string): string {
  let src = md.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");
  src = src.replace(/^---\\n[\\s\\S]*?\\n---\\n?/, "");

  const lines = src.split("\\n");
  const out: string[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (/^\\\`\\\`\\\`/.test(line)) {
      const lang = line.slice(3).trim();
      const codeLines: string[] = [];
      i++;
      while (i < lines.length && !/^\\\`\\\`\\\`/.test(lines[i])) {
        codeLines.push(escapeHtml(lines[i]));
        i++;
      }
      const langAttr = lang ? \` class="language-\${lang}"\` : "";
      out.push(\`<pre><code\${langAttr}>\${codeLines.join("\\n")}</code></pre>\`);
      i++;
      continue;
    }

    if (/^>/.test(line)) {
      const bqLines: string[] = [];
      while (i < lines.length && /^>/.test(lines[i])) {
        bqLines.push(lines[i].replace(/^>\\s?/, ""));
        i++;
      }
      out.push(\`<blockquote>\${renderMarkdown(bqLines.join("\\n"))}</blockquote>\`);
      continue;
    }

    const hMatch = line.match(/^(#{1,6})\\s+(.*)/);
    if (hMatch) {
      const level = hMatch[1].length;
      const text  = hMatch[2];
      const id    = text.toLowerCase().replace(/[^\\w\\s-]/g, "").replace(/\\s+/g, "-").replace(/^-+|-+$/g, "");
      out.push(\`<h\${level} id="\${id}">\${inline(text)}</h\${level}>\`);
      i++;
      continue;
    }

    if (/^(---+|\\*\\*\\*+|___+)\\s*$/.test(line)) { out.push("<hr>"); i++; continue; }

    if (/\\|/.test(line) && i + 1 < lines.length && /^\\|?[\\s:|-]+\\|/.test(lines[i + 1])) {
      const tableLines: string[] = [];
      while (i < lines.length && /\\|/.test(lines[i])) { tableLines.push(lines[i]); i++; }
      out.push(renderTable(tableLines));
      continue;
    }

    if (/^\\s*[*\\-+]\\s/.test(line)) {
      const listLines: string[] = [];
      while (i < lines.length && /^\\s*[*\\-+]\\s/.test(lines[i])) { listLines.push(lines[i]); i++; }
      out.push(renderList(listLines, false));
      continue;
    }

    if (/^\\s*\\d+\\.\\s/.test(line)) {
      const listLines: string[] = [];
      while (i < lines.length && /^\\s*\\d+\\.\\s/.test(lines[i])) { listLines.push(lines[i]); i++; }
      out.push(renderList(listLines, true));
      continue;
    }

    if (line.trim() === "") { i++; continue; }

    const paraLines: string[] = [];
    while (
      i < lines.length &&
      lines[i].trim() !== "" &&
      !/^[>#\\\`\\|*\\-+]/.test(lines[i]) &&
      !/^\\d+\\./.test(lines[i])
    ) { paraLines.push(lines[i]); i++; }

    if (paraLines.length) { out.push(\`<p>\${inline(paraLines.join(" "))}</p>\`); }
    else { i++; }
  }

  return out.join("\\n");
}

function renderList(lines: string[], ordered: boolean): string {
  const tag = ordered ? "ol" : "ul";
  const items = lines.map((l) => {
    const text = l.replace(/^\\s*([*\\-+]|\\d+\\.)\\s/, "");
    const taskMatch = text.match(/^\\[([ xX])\\]\\s(.*)/);
    if (taskMatch) {
      const checked = taskMatch[1].toLowerCase() === "x" ? " checked" : "";
      return \`<li><input type="checkbox" disabled\${checked}> \${inline(taskMatch[2])}</li>\`;
    }
    return \`<li>\${inline(text)}</li>\`;
  });
  return \`<\${tag}>\${items.join("")}</\${tag}>\`;
}

function renderTable(lines: string[]): string {
  const rows = lines.map((l) =>
    l.replace(/^\\|/, "").replace(/\\|$/, "").split("|").map((c) => c.trim())
  );
  if (rows.length < 2) return "";
  const head = rows[0].map((c) => \`<th>\${inline(c)}</th>\`).join("");
  const body = rows.slice(2).map((r) => \`<tr>\${r.map((c) => \`<td>\${inline(c)}</td>\`).join("")}</tr>\`).join("");
  return \`<table><thead><tr>\${head}</tr></thead><tbody>\${body}</tbody></table>\`;
}

function inline(text: string): string {
  return text
    .replace(/!\\[([^\\]]*)\\]\\(([^)]+)\\)/g, '<img src="$2" alt="$1">')
    .replace(/\\[([^\\]]+)\\]\\(([^)]+)\\)/g, '<a href="$2">$1</a>')
    .replace(/\\*\\*([^*]+)\\*\\*/g, "<strong>$1</strong>")
    .replace(/__([^_]+)__/g, "<strong>$1</strong>")
    .replace(/\\*([^*]+)\\*/g, "<em>$1</em>")
    .replace(/_([^_]+)_/g, "<em>$1</em>")
    .replace(/\\\`([^\\\`]+)\\\`/g, "<code>$1</code>")
    .replace(/~~([^~]+)~~/g, "<del>$1</del>")
    .replace(/  \\n/g, "<br>");
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
`;

const SITE_TREE_TS = `export interface TreeNode {
  name: string;
  path: string;
  depth: number;
  children?: TreeNode[];
}

const modules = import.meta.glob('/src/routes/**/+page.svelte');

function buildTree(): TreeNode[] {
  const paths = Object.keys(modules)
    .map(p => p.replace('/src/routes', '').replace('/+page.svelte', '').replace(/\\/$/, '') || '/')
    .filter(p => p !== '/');

  const root: TreeNode[] = [];

  for (const rawPath of paths.sort()) {
    const parts = rawPath.split('/').filter(Boolean);
    let currentLevel = root;

    parts.forEach((part, i) => {
      const isLeaf = i === parts.length - 1;
      const existing = currentLevel.find(n => n.name === part);
      const builtPath = '/' + parts.slice(0, i + 1).join('/');

      if (existing) {
        if (!isLeaf && !existing.children) existing.children = [];
        currentLevel = existing.children ?? [];
      } else {
        const node: TreeNode = {
          name: part,
          path: isLeaf ? builtPath + '/' : builtPath,
          depth: i + 1,
          children: isLeaf ? undefined : [],
        };
        currentLevel.push(node);
        currentLevel = node.children ?? [];
      }
    });
  }
  return root;
}

export const siteTree: TreeNode[] = buildTree();

export function flattenTree(nodes: TreeNode[]): TreeNode[] {
  const result: TreeNode[] = [];
  for (const node of nodes) {
    if (!node.children) result.push(node);
    else result.push(...flattenTree(node.children));
  }
  return result;
}
`;
